### ISSUE TITLE
[1.5 pt] Create Database Design

### ISSUE THREAD

**Issue by eapenzacharias** [Maha-Magdy/pick-a-doctor#1]
## Create A Database Design

- [ ] Decide apllication features
- [ ] Create database table
- [ ] Decide relation between tables
- [ ] Create ERD diagram

**Comment by Maha-Magdy** [comment]
we finalized the ERD design, and the following image represents it
![PICK-A-DOCTOR-ERD](https://user-images.githubusercontent.com/62838415/164783155-ab754246-9c5b-4647-938c-18c7fb5ca014.jpeg)
